name: Build & Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/YOUR_GITHUB_USERNAME/my-python-script:latest .

      - name: Push Docker image
        run: docker push ghcr.io/YOUR_GITHUB_USERNAME/my-python-script:latest
