name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Cache Docker layers  # ✅ Enable Docker layer caching for quicker builds.
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with correct tag
        run: |
          docker buildx build \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            -t ghcr.io/tddouglas/train-tracker:latest \
            --load . 

      - name: Verify Docker Image Exists (Debugging Step)
        run: docker images ghcr.io/tddouglas/train-tracker

      - name: Push Docker image
        run: docker push ghcr.io/tddouglas/train-tracker:latest

      - name: Save Docker image to tarball
        run: docker save ghcr.io/tddouglas/train-tracker:latest -o image.tar

      - name: Cache Docker image tarball  # Enable Image Caching for quicker runs
        uses: actions/cache@v4
        with:
          path: image.tar
          key: docker-image-tar-ghcr-latest