name: Build & Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Cache Docker layers  # ✅ Enable Docker layer caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image with cache
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            -t ghcr.io/tddouglas/train-tracker:latest .

      - name: Push Docker image
        run: docker push ghcr.io/tddouglas/train-tracker:latest
