name: Run Script Every 7 Minutes Using Docker

on:
  schedule:
    - cron: '*/7 * * * *'  # Runs every 7 minutes
  workflow_dispatch:  # 👈 Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Check if Docker image exists locally
        run: |
          if [[ "$(docker images -q ghcr.io/tddouglas/train-tracker:latest 2> /dev/null)" == "" ]]; then
            docker pull ghcr.io/tddouglas/train-tracker:latest
          else
            echo "Image already exists locally, skipping pull."
          fi

      - name: Run Docker container
        run: |
          docker run --rm \
            -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            -e SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }} \
            ghcr.io/tddouglas/train-tracker:latest